import { Move } from '../../../types/Pokemon';

const dragonpulse: Move = {
  id: 'dragonpulse',
  name: 'Dragon Pulse',
  type: 'Dragon',
  category: 'Special',
  power: 85,
  accuracy: 100,
  pp: 10,
  description: 'The foe is attacked with a shock wave generated by the user’s gaping mouth. ',
};

export default dragonpulse;
